In [2]:
import numpy as np


In [7]:
x1 = np.array([1,2,3])

y2 = np.array([[1,2,5],
              [3,6,9]])

print(x1)
print(y2)
print(type(x1))
print(type(y2))

[1 2 3]
[[1 2 5]
 [3 6 9]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


### np.eye로 생성하기

- N차 단위행렬(대각선의 원소가 모두 1이며 나머지 원소는 모두 0인 정사각 행렬) 생성

In [4]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### np.linspace 로 생성하기 (linear space)

In [6]:
# 1과 10을 포함 숫자 3개가 오도록 하는데 원소간의 차가 동일하도록 행렬 만들기

np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

In [ ]:
# 1과 10을 포함 숫자 4개가 오도록 하는데 원소간의 차가 동일하도록 행렬 만들기

np.linspace(1, 10, 4)


array([ 1.,  4.,  7., 10.])

In [8]:
# 1과 10을 포함해서 숫자 5개가 오도록 하는데 원소간의 차가 동일하도록 행렬 만들기
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### reshape 함수

- ndarray 행렬을 다른 차원으로 바꾸는데 사용

In [9]:
x = np.arange(1, 16)
print(x)

x.shape

x.reshape(3, 5) # 1차원 이었던 ndarray를 2차원(3행 5열)로 바꿔줌

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])