# ndarray 데이터 생성하기

In [1]:
import numpy as np

#### np.array 함수로 생성하기

In [4]:
x = np.array([1, 2, 3, 4])            # 1차원 행렬(벡터) 생성
print(x)

y = np.array([[2, 3, 4], [1, 2, 5]])  # 2차원 행렬 생성
print(y)

print(type(y))

[1 2 3 4]
[[2 3 4]
 [1 2 5]]
<class 'numpy.ndarray'>


#### np.arange 함수로 생성하기

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [9]:
np.arange(5, 101, 5)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

#### np.ones, np.zeros로 생성하기

In [12]:
# 4행 5열의 모든 원소값이 1인 행렬 만들기
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# 3행 4열이 2개인이고 모든 원소값이 1인 3차원 행렬 만들기
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [14]:
# 2행 3열의 모든 원소값이 0인 행렬 만들기
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
# 3행 8열이 2개인이고 모든 원소값이 0인 3차원 행렬 만들기
np.zeros((2, 3, 8))

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])

#### np.empty, np.full로 생성하기

In [15]:
# 어떤 값이든 상관 없고 초기화된 값을 갖고자 할 경우
np.empty((3, 4))

array([[1.17626560e-311, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.12465777e-312, 1.04082753e-047, 6.50573804e-091,
        4.31795924e-061],
       [2.32715902e-057, 1.16436476e+165, 3.99910963e+252,
        5.82471487e+257]])

In [16]:
# 3행 4열의 모든 원소값이 7인 행렬 만들기
np.full((3, 4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [17]:
np.full((3, 4, 2), 7)

array([[[7, 7],
        [7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7],
        [7, 7]]])

In [20]:
from sklearn.preprocessing import normalize

data = np.array(

[[1000, -10, -0.5],

 [760, 5, 0.3],

 [800, 7, 0.1]])


data = normalize(data, axis=0, norm='max')
print(data)


[[ 1.   -1.   -1.  ]
 [ 0.76  0.5   0.6 ]
 [ 0.8   0.7   0.2 ]]


#### np.eye로 생성하기
 - N차 단위행렬(대각선의 원소가 모두 1이며 나머지 원소는 모두 0인 정사각 행렬) 생성

In [22]:
# 5행 5열의 행렬의 대각선의 원소값만 1이고 나머지는 0인 행렬 만들기
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### np.linspace로 생성하기 (linear space)

In [23]:
# 1과 10을 포함해서 숫자 3개가 오도록 하는데 원소간의 차(spacing)가 동일 하도록 행렬 만들기
np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

In [24]:
# 1과 10을 포함해서 숫자 4개가 오도록 하는데 원소간의 차(spacing)가 동일 하도록 행렬 만들기
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

In [25]:
# 1과 10을 포함해서 숫자 5개가 오도록 하는데 원소간의 차(spacing)가 동일 하도록 행렬 만들기
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

#### reshape 함수
 - ndarray 행렬을 다른 차원으로 바꾸는데 사용

In [26]:
x = np.arange(1, 16)  # 1차원 ndarray 생성
print(x)

x.shape

x.reshape(3, 5)  # 1차원 이었던 ndarray를 2차원(3행 5열)의 ndarray 형태로 변경 함 

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [29]:
x = np.arange(1, 16)  # 1차원 ndarray 생성
print(x)

x.shape

x.reshape(5, 3, 1)  # 1차원 이었던 ndarray를 3차원(3행 1열, 5개)의 ndarray 형태로 변경 함 
# x.reshape(5,3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [30]:
x = np.arange(1, 16)  # 1차원 ndarray 생성
print(x)

x.shape

x.reshape(5, 4)  # 5*4 = 20 과 1~15까지의 숫자와 같이 않으면 에러 발생

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


ValueError: cannot reshape array of size 15 into shape (5,4)