# ndarray 인덱싱과 슬라이싱


In [1]:
import numpy as np

#### 인덱싱
 - 리스트 인덱싱과 동일한 개념으로 사용
 - , 를 사용하여 각 차원의 인덱스에 접근 가능

 * 1차원 행렬(벡터) 인덱싱

In [2]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
x[0]

0

In [4]:
x[-1]

9

In [5]:
x[3] = 100
print(x)

[  0   1   2 100   4   5   6   7   8   9]


* 2차원 행렬 인덱싱

In [6]:
x = np.arange(10).reshape(2, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [7]:
x[0]

array([0, 1, 2, 3, 4])

In [8]:
x[1]

array([5, 6, 7, 8, 9])

In [9]:
x[0,2]  # 0번째 행의 2번째 열

2

In [10]:
x[1,2]  # 1번째 행의 2번째 열

7

In [11]:
x[1,-1]  # 1번째 행의 마지막 원소

9

* 3차원 텐서 인덱싱

In [9]:
x = np.arange(36).reshape(3, 4, 3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [19]:
x[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
x[1, 2]

array([18, 19, 20])

In [13]:
x[1, 2, 1]

19

#### 슬라이싱
 - 리스트, 문자열 slicing과 동일한 개념으로 사용
 - ,를 사용하여 각 차원 별로 슬라이싱 가능

* 1차원 벡터 슬라이싱

In [22]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
x[1:7]  # index 7은 포함하지 않는다.

array([1, 2, 3, 4, 5, 6])

In [10]:
x[1:]  # index 1부터 끝까지

array([[[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [25]:
x[:]  # index 처음부터 끝까지

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

* 2차원 행렬 슬라이싱

In [26]:
x = np.arange(10).reshape(2, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [27]:
x[:, 1:4]  # 모든 행을 가져오고, 1~3열 맨 끝에 숫자(4)는 제외

array([[1, 2, 3],
       [6, 7, 8]])

In [28]:
x[:, :2] # 모든 행을 가져오고, 0~1열 맨 끝에 숫자(2)는 제외

array([[0, 1],
       [5, 6]])

In [29]:
x[0, :2] # indexing을 하면 차원이 하나 줄어 듬, 결과는 1차원 벡터

array([0, 1])

In [31]:
x[:1, :2] # slicing을 하면 차원을 그대로 유지 하면서 자른다.

array([[0, 1]])

* 3차원 텐서 슬라이싱

In [32]:
x = np.arange(54).reshape(2, 9, 3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]
  [48 49 50]
  [51 52 53]]]


In [33]:
x[:1, :2, :]  # slicing은 차원을 유지하면서 자름(3차원)

array([[[0, 1, 2],
        [3, 4, 5]]])

In [34]:
x[0, :2, :]  # indexing을 하면 차원이 하나 줄어듬(2차원)

array([[0, 1, 2],
       [3, 4, 5]])