# numpy 기본함수

In [2]:
import numpy as np

#### numpy documentation
 - [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
 - numpy에서 제공되는 함수 등에 대한 문서

#### 연산 함수
 - add, substract, multiply, divide
 - ndarray 끼리의 연산은 둘 다 shape이 같아야 함

In [3]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.58040454 0.20674278 0.27479745 0.50866574 0.51950138]
 [0.91795984 0.99147825 0.04907966 0.9388926  0.8368884 ]
 [0.57730593 0.13173178 0.95124296 0.02592222 0.58483396]]


In [4]:
np.add(x, y)  # 인덱스가 같은 원소끼리 더한다.

array([[ 0.38814617,  1.63343939,  2.28695194,  3.57973967,  4.39148519],
       [ 5.43540389,  6.99183038,  7.67455604,  8.45234919,  9.48750027],
       [10.99998452, 11.42471324, 12.93116388, 13.08271919, 14.91550565]])

In [5]:
np.divide(x, y)

array([[  0.        ,   1.57868301,   6.96980831,   5.1747364 ,
         10.21750019],
       [ 11.48359043,   6.04942145,  10.37719565,  17.68545209,
         18.46152812],
       [ 10.00015479,  25.89982846,  12.88709775, 157.1582163 ,
         15.29209563]])

In [6]:
x + y  # 바로 연산자 이용 가능, 단 ndarray 끼리의 연산은 그 두개의 ndarray가 shape 이 같아야 한다.

array([[ 0.38814617,  1.63343939,  2.28695194,  3.57973967,  4.39148519],
       [ 5.43540389,  6.99183038,  7.67455604,  8.45234919,  9.48750027],
       [10.99998452, 11.42471324, 12.93116388, 13.08271919, 14.91550565]])

In [7]:
x * y # 바로 연산자 이용 가능, 단 ndarray 끼리의 연산은 그 두개의 ndarray가 shape 이 같아야 한다.

array([[ 0.        ,  0.63343939,  0.57390388,  1.73921902,  1.56594076],
       [ 2.17701947,  5.9509823 ,  4.72189228,  3.61879355,  4.38750246],
       [ 9.99984521,  4.67184561, 11.17396661,  1.07534944, 12.81707915]])

#### 통계 함수
 - 평균, 분산, 중앙값, 최대값, 최소값 등 통계 관련된 함수

In [8]:
print(y)

[[0.38814617 0.63343939 0.28695194 0.57973967 0.39148519]
 [0.43540389 0.99183038 0.67455604 0.45234919 0.48750027]
 [0.99998452 0.42471324 0.93116388 0.08271919 0.91550565]]


In [9]:
np.mean(y)  # 평균 계산

0.578365908618126

In [10]:
y.mean()  # 평균 계산

0.578365908618126

In [11]:
np.max(y) # 최대값

0.9999845212418148

In [12]:
np.argmax(y) # 최대값의 index

10

In [13]:
np.var(y), np.median(y), np.std(y)  # 분산, 중앙값, 표준편차

(0.07126746977349335, 0.4875002731850382, 0.2669596781791088)

#### 집계함수
 - 합계(sum), 누적합계(cumsum) 등

In [14]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
np.sum(x)  # 모든 원소의 합계

105

In [16]:
np.cumsum(x) # n번째 원소(누적합) = n-1번째 원소까지의 누적합 + n번째 원소

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105], dtype=int32)

#### any, all 함수
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [17]:
z = np.random.randn(10)
print(z)

[ 1.82058944  0.32319609 -1.71691151 -0.46626336 -0.0622571  -0.36593082
  0.744948   -0.26682209 -0.19206059  0.03614001]


In [18]:
z > 0  # 각 원소를 Boolean array 로 저장

array([ True,  True, False, False, False, False,  True, False, False,
        True])

In [19]:
np.any(z > 0)  # 조건이 하나라도 참이면 True

True

In [20]:
np.all(z > 0)  # 모두 참이여야만 True

False

In [21]:
np.all(z != 0)  # 모두 참이여야만 True

True

#### where 함수
 - 조건에 따라 행렬 각 원소의 값을 선택하여 설정할 수 있음
 - np.where(조건, 참일때 선택값, 거짓일때 선택값)

In [22]:
z = np.random.randn(10)
print(z)

[-0.41339424 -0.40209333  2.84874199  0.6380972  -0.21417078  1.25205107
 -0.7134561  -0.14563798 -1.43635103  1.13517431]


In [23]:
# np.where(조건, 참값, 거짓값)
np.where(z > 0, z, 0)  # 조건을 만족하면 z 값을 그대로 쓰고, 거짓이면 0으로 대치함

array([0.        , 0.        , 2.84874199, 0.6380972 , 0.        ,
       1.25205107, 0.        , 0.        , 0.        , 1.13517431])