# axis를 파라미터로 갖는 함수

In [2]:
import numpy as np

#### axis 파라미터
 - 대부분의 연산함수에는 axis 파라미터가 존재(np.sum, np.mean 등)
 - axis 파라미터가 없는 경우에는 전체 원소에 대해 연산이 적용
 - axis 파라미터가 있는 경우에는, 해당 axis를 축으로 연산이 적용
   + 1차원 행렬(벡터)
      * axis = 0 : 1차원에서 axis 의 최대값은 0
   + 2차원 행렬   
      * axis = 0 : 행 증가 방향
      * axis = 1 : 열 증가 방향
   + 3차원(텐서) 행렬
      * axis = 0 : 행렬 단위
      * axis = 1 : 행 증가 방향
      * axis = 2 : 열 증가 방향
 - 해당 axis가 제외된 나머지 차원의 shape로 연산 결과가 남게 됨    

In [2]:
x = np.arange(15)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


* 1차원 행렬(벡터)에서의 axis 사용

In [3]:
np.sum(x, axis=0) # 1차원이라 축이 하나고, 축을 따라서 합계를 구한다. 1차원일때 축의 최대값은 0.

105

In [4]:
np.sum(x, axis=1) # 1차원일때 축의 최대값은 0

AxisError: axis 1 is out of bounds for array of dimension 1

* 2차원 행렬에서의 axis 사용

In [5]:
y = x.reshape(3, 5)   # 행렬에서는 행이 증가하는 방향이 0, 열이 증가하는 방향이 1.
print(y)

np.sum(y)  # 행렬 전체에 대한 합계

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


105

In [6]:
y = x.reshape(3, 5)   # 행렬에서는 행이 증가하는 방향이 0, 열이 증가하는 방향이 1.
print(y)
np.sum(y, axis=0)  # 행방향을 따라서 합계를 구함, 크기가 5인 벡터 생성

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([15, 18, 21, 24, 27])

In [7]:
y = x.reshape(3, 5)   # 행렬에서는 행이 증가하는 방향이 0, 열이 증가하는 방향이 1.
print(y)
np.sum(y, axis=1)  # 열방향을 따라서 합계를 구함, 크기가 3인 벡터 생성

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([10, 35, 60])

* 3차원 행렬(텐서)에서의 axis 사용

In [8]:
z = np.arange(36).reshape(3, 4, 3)
print(z)

np.sum(z)  # 원소 모두 더하기

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


630

In [9]:
z = np.arange(36).reshape(3, 4, 3)
print(z)

np.sum(z, axis=0)  # (4,3) 행렬이 도출

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


array([[36, 39, 42],
       [45, 48, 51],
       [54, 57, 60],
       [63, 66, 69]])

In [11]:
z = np.arange(36).reshape(3, 4, 3)
print(z)

np.sum(z, axis=1) # (3,3) 행렬이 도출

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


array([[ 18,  22,  26],
       [ 66,  70,  74],
       [114, 118, 122]])

In [12]:
z = np.arange(36).reshape(3, 4, 3)
print(z)

np.sum(z, axis=2) # (3,4) 행렬이 도출

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


array([[  3,  12,  21,  30],
       [ 39,  48,  57,  66],
       [ 75,  84,  93, 102]])

In [13]:
np.sum(z, axis=-1)  # axis=-1 은 axis=2 와 동일  

array([[  3,  12,  21,  30],
       [ 39,  48,  57,  66],
       [ 75,  84,  93, 102]])

In [14]:
np.sum(z, axis=-3)  # axis=-3 은 axis=0 와 동일

array([[36, 39, 42],
       [45, 48, 51],
       [54, 57, 60],
       [63, 66, 69]])

* axis의 값이 튜플일 경우
 - 해당 튜플에 명시된 모든 axis에 대해서 연산

In [15]:
print(z)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [16]:
np.sum(z, axis=(0, 1))  # 크기가 3인 벡터만 도출

array([198, 210, 222])

In [17]:
np.sum(z, axis=(0, 2))  # 크기가 4인 벡터만 도출

array([117, 144, 171, 198])