# Boolean indexing

#### Boolean indexing
  - ndarray indexing에 있어서 bool 리스트를 index로 전달하여 True 위치에 해당하는 값만 가져 오도록 필터링 

In [1]:
import numpy as np

In [2]:
x = np.random.randint(1, 100, size=10)
print(x)

[ 3 20 83 17 16 27 41 86 52 77]


In [3]:
even_mask = x % 2 == 0  # 모든 원소에 Boolean 를 적용 함, 크기가 동일한(10) Boolean ndarray 가 생성됨
print(even_mask)

[False  True False False  True False False  True  True False]


- ndarray 인덱싱에 bool 리스트를 인덱스로 전달하기

In [4]:
x[even_mask]  # even_mask에 True 위치의 값만 가져온다, even_mask 는 마치 필터 역할을 한다. 

array([20, 16, 86, 52])

In [5]:
x[x % 2 == 0]  # even_mask 를 만들지 않고 직접 작성이 가능하다.

array([20, 16, 86, 52])

In [6]:
x[x > 30]  # 30 보다 큰수를 가져오도록 한다.

array([83, 41, 86, 52, 77])

####  ndarray 인덱싱에 다중조건 사용하기
 - 파이썬 논리 연산자 and, or, not 키워드 사용 불가
 - & - AND 
 - | - OR 

In [7]:
x % 2 == 0  # 짝수
x < 30      # 30보다 작은

x[(x % 2 == 0) & (x < 30)]  # 두 조건의 and 조건

array([20, 16])

In [8]:
x < 30  # 30보다 작고
x > 50  # 50보다 크고

x[(x < 30) | (x > 50)]  # 두 조건의 or 조건

array([ 3, 20, 83, 17, 16, 27, 86, 52, 77])

#### not 키워드는 조건을 반대로 하여 기재하면 됨

#### 예제) 2020년 7월 서울 평균기온 데이터
 - 평균기온이 25도를 넘는 날수는?
 - 평균기온이 25를 넘는 날의 평균 기온은?

In [9]:
temp = np.array(
        [23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
         26.7, 25.1, 25.0, 22.7, 21.9, 23.6, 
         24.9, 25.9, 23.8, 24.7, 25.6, 26.9, 
         28.6, 28.0, 25.1, 26.7, 28.1, 26.5, 
         26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

In [10]:
len(temp)

31

In [11]:
len(temp[temp > 25.0])

21

In [12]:
temp > 25.0

array([False, False, False,  True,  True,  True,  True,  True, False,
       False, False, False, False,  True, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [15]:
np.sum(temp > 25.0)  # True 가 1 임으로 모두 더하면 날의 수를 구할 수 있다.

21

In [13]:
np.mean(temp[temp > 25.0])

26.857142857142858